--
-- PostgreSQL database dump
--

\restrict 9MmMZHTI82twKUy7gpiJj8TLdrQ4C7cpF5nktIls8bZe6ckdkKgb880tNq3SJov

-- Dumped from database version 17.7
-- Dumped by pg_dump version 17.7

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.pago_cuota DROP CONSTRAINT IF EXISTS fkona6b6cajwjn2lqkr95trkcrv;
ALTER TABLE IF EXISTS ONLY public.cuota DROP CONSTRAINT IF EXISTS fkocea2qlrxeulerh5wkgdhyyik;
ALTER TABLE IF EXISTS ONLY public.persona DROP CONSTRAINT IF EXISTS fkmshhft3asgvpt2u71cf9483ka;
ALTER TABLE IF EXISTS ONLY public.persona_promocion DROP CONSTRAINT IF EXISTS fkl6nnohdju6ka8bdm558qj7agj;
ALTER TABLE IF EXISTS ONLY public.pago DROP CONSTRAINT IF EXISTS fkki2hy7gnk8j4scgmqj3qh2162;
ALTER TABLE IF EXISTS ONLY public.persona_deporte DROP CONSTRAINT IF EXISTS fkkdew6r88jwwlml0rg3k9jo42g;
ALTER TABLE IF EXISTS ONLY public.persona_deporte DROP CONSTRAINT IF EXISTS fkiok40h87oe8u8rnd32t7isgcl;
ALTER TABLE IF EXISTS ONLY public.persona_promocion DROP CONSTRAINT IF EXISTS fkf73wrhco05aipr0b5y32ocpgb;
ALTER TABLE IF EXISTS ONLY public.cuota DROP CONSTRAINT IF EXISTS fkdwafq9vpj57ps69rem4i1cbvw;
ALTER TABLE IF EXISTS ONLY public.pago_cuota DROP CONSTRAINT IF EXISTS fk9wpvxss35vof27ekodka385h7;
ALTER TABLE IF EXISTS ONLY public.inscripcion DROP CONSTRAINT IF EXISTS fk95i27mad61mfln42rdbhkqpv9;
ALTER TABLE IF EXISTS ONLY public.inscripcion DROP CONSTRAINT IF EXISTS fk39ckmo4kmunuvq79gk53kuhyb;
ALTER TABLE IF EXISTS ONLY public.cuota DROP CONSTRAINT IF EXISTS fk2scsr6kub5gepf6gxci8v8r9k;
ALTER TABLE IF EXISTS ONLY public.usuario DROP CONSTRAINT IF EXISTS usuario_pkey;
ALTER TABLE IF EXISTS ONLY public.deporte DROP CONSTRAINT IF EXISTS ukp8csicfrqofd738h7ufq9lwxq;
ALTER TABLE IF EXISTS ONLY public.promocion DROP CONSTRAINT IF EXISTS ukolxj0a61psjh8qftd1iw3a0en;
ALTER TABLE IF EXISTS ONLY public.persona DROP CONSTRAINT IF EXISTS ukhlwyecu2r9wagqayhej1kt5wy;
ALTER TABLE IF EXISTS ONLY public.pago_cuota DROP CONSTRAINT IF EXISTS uk_pago_cuota_cuota_id;
ALTER TABLE IF EXISTS ONLY public.cuota DROP CONSTRAINT IF EXISTS uk_cuota_persona_deporte_periodo;
ALTER TABLE IF EXISTS ONLY public.registro DROP CONSTRAINT IF EXISTS uk8oy68l6vmfnl2cvnoubr60jr3;
ALTER TABLE IF EXISTS ONLY public.usuario DROP CONSTRAINT IF EXISTS uk863n1y3x0jalatoir4325ehal;
ALTER TABLE IF EXISTS ONLY public.registro DROP CONSTRAINT IF EXISTS registro_pkey;
ALTER TABLE IF EXISTS ONLY public.promocion DROP CONSTRAINT IF EXISTS promocion_pkey;
ALTER TABLE IF EXISTS ONLY public.persona_promocion DROP CONSTRAINT IF EXISTS persona_promocion_pkey;
ALTER TABLE IF EXISTS ONLY public.persona DROP CONSTRAINT IF EXISTS persona_pkey;
ALTER TABLE IF EXISTS ONLY public.persona_deporte DROP CONSTRAINT IF EXISTS persona_deporte_pkey;
ALTER TABLE IF EXISTS ONLY public.pago DROP CONSTRAINT IF EXISTS pago_pkey;
ALTER TABLE IF EXISTS ONLY public.pago_cuota DROP CONSTRAINT IF EXISTS pago_cuota_pkey;
ALTER TABLE IF EXISTS ONLY public.inscripcion DROP CONSTRAINT IF EXISTS inscripcion_pkey;
ALTER TABLE IF EXISTS ONLY public.deporte DROP CONSTRAINT IF EXISTS deporte_pkey;
ALTER TABLE IF EXISTS ONLY public.cuota DROP CONSTRAINT IF EXISTS cuota_pkey;
ALTER TABLE IF EXISTS ONLY public.audit_log DROP CONSTRAINT IF EXISTS audit_log_pkey;
DROP TABLE IF EXISTS public.usuario;
DROP TABLE IF EXISTS public.registro;
DROP TABLE IF EXISTS public.promocion;
DROP TABLE IF EXISTS public.persona_promocion;
DROP TABLE IF EXISTS public.persona_deporte;
DROP TABLE IF EXISTS public.persona;
DROP TABLE IF EXISTS public.pago_cuota;
DROP TABLE IF EXISTS public.pago;
DROP SEQUENCE IF EXISTS public.inscripcion_seq;
DROP TABLE IF EXISTS public.inscripcion;
DROP TABLE IF EXISTS public.deporte;
DROP TABLE IF EXISTS public.cuota;
DROP TABLE IF EXISTS public.audit_log;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    event character varying(255) NOT NULL,
    "timestamp" timestamp(6) with time zone NOT NULL,
    username character varying(255) NOT NULL
);


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cuota; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cuota (
    id bigint NOT NULL,
    estado character varying(255) NOT NULL,
    fecha_generacion date NOT NULL,
    fecha_vencimiento date,
    monto numeric(10,2) NOT NULL,
    periodo date NOT NULL,
    deporte_id bigint NOT NULL,
    persona_id bigint NOT NULL,
    concepto text,
    pago_id bigint,
    cuota_entrenador numeric(10,2) NOT NULL,
    cuota_seguro numeric(10,2) NOT NULL,
    cuota_social numeric(10,2) NOT NULL,
    CONSTRAINT cuota_estado_check CHECK (((estado)::text = ANY (ARRAY[('GENERADA'::character varying)::text, ('VENCIDA'::character varying)::text, ('PAGADA'::character varying)::text])))
);


--
-- Name: cuota_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cuota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deporte; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.deporte (
    id bigint NOT NULL,
    cuota_mensual numeric(10,2) NOT NULL,
    descripcion text,
    nombre character varying(100) NOT NULL,
    cuota_entrenador numeric(10,2) NOT NULL,
    cuota_seguro numeric(10,2) NOT NULL,
    cuota_social numeric(10,2) NOT NULL
);


--
-- Name: deporte_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.deporte ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deporte_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inscripcion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inscripcion (
    id bigint NOT NULL,
    fecha_baja date,
    fecha_inscripcion date NOT NULL,
    deporte_id bigint NOT NULL,
    persona_id bigint NOT NULL
);


--
-- Name: inscripcion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.inscripcion_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: pago; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pago (
    id bigint NOT NULL,
    conceptos jsonb,
    fecha_pago date NOT NULL,
    metodo_pago character varying(255),
    monto_total numeric(10,2) NOT NULL,
    observaciones text,
    socio_id bigint NOT NULL,
    monto_descuento numeric(10,2) DEFAULT 0 NOT NULL,
    monto_original numeric(10,2) DEFAULT 0 NOT NULL,
    cuota_entrenador numeric(10,2) NOT NULL,
    cuota_seguro numeric(10,2) NOT NULL,
    cuota_social numeric(10,2) NOT NULL,
    CONSTRAINT pago_metodo_pago_check CHECK (((metodo_pago)::text = ANY (ARRAY[('EFECTIVO'::character varying)::text, ('TRANSFERENCIA'::character varying)::text, ('DEBITO_AUTOMATICO'::character varying)::text])))
);


--
-- Name: pago_cuota; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pago_cuota (
    id bigint NOT NULL,
    monto_aplicado numeric(10,2) NOT NULL,
    cuota_id bigint NOT NULL,
    pago_id bigint NOT NULL
);


--
-- Name: pago_cuota_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pago_cuota ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pago_cuota_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pago_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persona (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    apellido character varying(255) NOT NULL,
    categoria character varying(255) NOT NULL,
    direccion character varying(255),
    dni character varying(255) NOT NULL,
    email character varying(255),
    fecha_nacimiento date,
    fecha_registro timestamp(6) with time zone NOT NULL,
    nombre character varying(255) NOT NULL,
    telefono character varying(255),
    socio_responsable_id bigint,
    CONSTRAINT persona_categoria_check CHECK (((categoria)::text = ANY (ARRAY[('SOCIO'::character varying)::text, ('JUGADOR'::character varying)::text, ('SOCIOYJUGADOR'::character varying)::text])))
);


--
-- Name: persona_deporte; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persona_deporte (
    persona_id bigint NOT NULL,
    deporte_id bigint NOT NULL
);


--
-- Name: persona_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.persona ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.persona_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: persona_promocion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.persona_promocion (
    persona_id bigint NOT NULL,
    promocion_id bigint NOT NULL
);


--
-- Name: promocion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.promocion (
    id bigint NOT NULL,
    activo boolean NOT NULL,
    descripcion text,
    descuento numeric(10,2) NOT NULL,
    nombre character varying(100) NOT NULL,
    tipo_descuento character varying(255) NOT NULL,
    CONSTRAINT promocion_tipo_descuento_check CHECK (((tipo_descuento)::text = ANY (ARRAY[('PORCENTAJE'::character varying)::text, ('MONTO_FIJO'::character varying)::text])))
);


--
-- Name: promocion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.promocion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promocion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: registro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registro (
    id bigint NOT NULL,
    apellido character varying(255) NOT NULL,
    dni character varying(255) NOT NULL,
    fecha_registro timestamp(6) with time zone NOT NULL,
    nombre character varying(255) NOT NULL,
    fecha_baja timestamp(6) with time zone,
    observacion_baja text
);


--
-- Name: registro_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.registro ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.registro_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    bloqueado boolean DEFAULT false NOT NULL,
    intentos_fallidos integer DEFAULT 0 NOT NULL,
    ultimo_acceso timestamp(6) with time zone,
    ultimo_intento_fallido timestamp(6) with time zone,
    CONSTRAINT usuario_role_check CHECK (((role)::text = ANY (ARRAY[('ADMIN'::character varying)::text, ('SECRETARIO'::character varying)::text])))
);


--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: audit_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.audit_log (id, event, "timestamp", username) FROM stdin;
\.


--
-- Data for Name: cuota; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cuota (id, estado, fecha_generacion, fecha_vencimiento, monto, periodo, deporte_id, persona_id, concepto, pago_id, cuota_entrenador, cuota_seguro, cuota_social) FROM stdin;
34	PAGADA	2026-01-12	2026-02-01	8000.00	2026-01-01	21	82		18	2500.00	2500.00	5000.00
\.


--
-- Data for Name: deporte; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.deporte (id, cuota_mensual, descripcion, nombre, cuota_entrenador, cuota_seguro, cuota_social) FROM stdin;
21	10000.00		Voley	2500.00	2500.00	5000.00
\.


--
-- Data for Name: inscripcion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.inscripcion (id, fecha_baja, fecha_inscripcion, deporte_id, persona_id) FROM stdin;
603	\N	2026-01-12	21	82
\.


--
-- Data for Name: pago; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pago (id, conceptos, fecha_pago, metodo_pago, monto_total, observaciones, socio_id, monto_descuento, monto_original, cuota_entrenador, cuota_seguro, cuota_social) FROM stdin;
18	\N	2026-01-12	EFECTIVO	8000.00	\N	82	0.00	0.00	2500.00	2500.00	5000.00
\.


--
-- Data for Name: pago_cuota; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pago_cuota (id, monto_aplicado, cuota_id, pago_id) FROM stdin;
\.


--
-- Data for Name: persona; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.persona (id, activo, apellido, categoria, direccion, dni, email, fecha_nacimiento, fecha_registro, nombre, telefono, socio_responsable_id) FROM stdin;
82	t	Marchione	SOCIO	\N	46150362	\N	2004-11-03	2026-01-12 11:47:37.497319-03	Lorenzo	\N	\N
\.


--
-- Data for Name: persona_deporte; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.persona_deporte (persona_id, deporte_id) FROM stdin;
82	21
\.


--
-- Data for Name: persona_promocion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.persona_promocion (persona_id, promocion_id) FROM stdin;
82	7
\.


--
-- Data for Name: promocion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.promocion (id, activo, descripcion, descuento, nombre, tipo_descuento) FROM stdin;
7	t	Testing	20.00	Promocion Prueba	PORCENTAJE
\.


--
-- Data for Name: registro; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.registro (id, apellido, dni, fecha_registro, nombre, fecha_baja, observacion_baja) FROM stdin;
27	Marchione	46150362	2026-01-12 11:47:37.497319-03	Lorenzo	\N	\N
\.


--
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuario (id, password_hash, role, username, activo, bloqueado, intentos_fallidos, ultimo_acceso, ultimo_intento_fallido) FROM stdin;
1	CambioSeguro2025	ADMIN	nuevo.admin	t	f	0	\N	\N
3	$2a$10$tuF/tAL5rMqmLDyEkSBFeuQZkWc.c5e9.55.rHTy3dEd72eceYrsK	SECRETARIO	secretario	t	f	0	\N	\N
2	$2a$10$xizv4xhAHGqYv1jxbZ/wNuwpK/8Dj/eTYfIVxxhjXX5dFOayoGDmG	ADMIN	admin	t	f	0	\N	\N
\.


--
-- Name: audit_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.audit_log_id_seq', 1, false);


--
-- Name: cuota_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cuota_id_seq', 34, true);


--
-- Name: deporte_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.deporte_id_seq', 21, true);


--
-- Name: inscripcion_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.inscripcion_seq', 651, true);


--
-- Name: pago_cuota_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pago_cuota_id_seq', 1, false);


--
-- Name: pago_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pago_id_seq', 18, true);


--
-- Name: persona_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.persona_id_seq', 82, true);


--
-- Name: promocion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.promocion_id_seq', 7, true);


--
-- Name: registro_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.registro_id_seq', 27, true);


--
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuario_id_seq', 3, true);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: cuota cuota_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuota
    ADD CONSTRAINT cuota_pkey PRIMARY KEY (id);


--
-- Name: deporte deporte_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deporte
    ADD CONSTRAINT deporte_pkey PRIMARY KEY (id);


--
-- Name: inscripcion inscripcion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inscripcion
    ADD CONSTRAINT inscripcion_pkey PRIMARY KEY (id);


--
-- Name: pago_cuota pago_cuota_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago_cuota
    ADD CONSTRAINT pago_cuota_pkey PRIMARY KEY (id);


--
-- Name: pago pago_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT pago_pkey PRIMARY KEY (id);


--
-- Name: persona_deporte persona_deporte_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_deporte
    ADD CONSTRAINT persona_deporte_pkey PRIMARY KEY (persona_id, deporte_id);


--
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (id);


--
-- Name: persona_promocion persona_promocion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_promocion
    ADD CONSTRAINT persona_promocion_pkey PRIMARY KEY (persona_id, promocion_id);


--
-- Name: promocion promocion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promocion
    ADD CONSTRAINT promocion_pkey PRIMARY KEY (id);


--
-- Name: registro registro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registro
    ADD CONSTRAINT registro_pkey PRIMARY KEY (id);


--
-- Name: usuario uk863n1y3x0jalatoir4325ehal; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username);


--
-- Name: registro uk8oy68l6vmfnl2cvnoubr60jr3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registro
    ADD CONSTRAINT uk8oy68l6vmfnl2cvnoubr60jr3 UNIQUE (dni);


--
-- Name: cuota uk_cuota_persona_deporte_periodo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuota
    ADD CONSTRAINT uk_cuota_persona_deporte_periodo UNIQUE (persona_id, deporte_id, periodo);


--
-- Name: pago_cuota uk_pago_cuota_cuota_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago_cuota
    ADD CONSTRAINT uk_pago_cuota_cuota_id UNIQUE (cuota_id);


--
-- Name: persona ukhlwyecu2r9wagqayhej1kt5wy; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT ukhlwyecu2r9wagqayhej1kt5wy UNIQUE (dni);


--
-- Name: promocion ukolxj0a61psjh8qftd1iw3a0en; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.promocion
    ADD CONSTRAINT ukolxj0a61psjh8qftd1iw3a0en UNIQUE (nombre);


--
-- Name: deporte ukp8csicfrqofd738h7ufq9lwxq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.deporte
    ADD CONSTRAINT ukp8csicfrqofd738h7ufq9lwxq UNIQUE (nombre);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- Name: cuota fk2scsr6kub5gepf6gxci8v8r9k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuota
    ADD CONSTRAINT fk2scsr6kub5gepf6gxci8v8r9k FOREIGN KEY (pago_id) REFERENCES public.pago(id);


--
-- Name: inscripcion fk39ckmo4kmunuvq79gk53kuhyb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inscripcion
    ADD CONSTRAINT fk39ckmo4kmunuvq79gk53kuhyb FOREIGN KEY (deporte_id) REFERENCES public.deporte(id);


--
-- Name: inscripcion fk95i27mad61mfln42rdbhkqpv9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inscripcion
    ADD CONSTRAINT fk95i27mad61mfln42rdbhkqpv9 FOREIGN KEY (persona_id) REFERENCES public.persona(id);


--
-- Name: pago_cuota fk9wpvxss35vof27ekodka385h7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago_cuota
    ADD CONSTRAINT fk9wpvxss35vof27ekodka385h7 FOREIGN KEY (pago_id) REFERENCES public.pago(id);


--
-- Name: cuota fkdwafq9vpj57ps69rem4i1cbvw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuota
    ADD CONSTRAINT fkdwafq9vpj57ps69rem4i1cbvw FOREIGN KEY (deporte_id) REFERENCES public.deporte(id);


--
-- Name: persona_promocion fkf73wrhco05aipr0b5y32ocpgb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_promocion
    ADD CONSTRAINT fkf73wrhco05aipr0b5y32ocpgb FOREIGN KEY (promocion_id) REFERENCES public.promocion(id);


--
-- Name: persona_deporte fkiok40h87oe8u8rnd32t7isgcl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_deporte
    ADD CONSTRAINT fkiok40h87oe8u8rnd32t7isgcl FOREIGN KEY (deporte_id) REFERENCES public.deporte(id);


--
-- Name: persona_deporte fkkdew6r88jwwlml0rg3k9jo42g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_deporte
    ADD CONSTRAINT fkkdew6r88jwwlml0rg3k9jo42g FOREIGN KEY (persona_id) REFERENCES public.persona(id);


--
-- Name: pago fkki2hy7gnk8j4scgmqj3qh2162; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago
    ADD CONSTRAINT fkki2hy7gnk8j4scgmqj3qh2162 FOREIGN KEY (socio_id) REFERENCES public.persona(id);


--
-- Name: persona_promocion fkl6nnohdju6ka8bdm558qj7agj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona_promocion
    ADD CONSTRAINT fkl6nnohdju6ka8bdm558qj7agj FOREIGN KEY (persona_id) REFERENCES public.persona(id);


--
-- Name: persona fkmshhft3asgvpt2u71cf9483ka; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT fkmshhft3asgvpt2u71cf9483ka FOREIGN KEY (socio_responsable_id) REFERENCES public.persona(id);


--
-- Name: cuota fkocea2qlrxeulerh5wkgdhyyik; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cuota
    ADD CONSTRAINT fkocea2qlrxeulerh5wkgdhyyik FOREIGN KEY (persona_id) REFERENCES public.persona(id);


--
-- Name: pago_cuota fkona6b6cajwjn2lqkr95trkcrv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pago_cuota
    ADD CONSTRAINT fkona6b6cajwjn2lqkr95trkcrv FOREIGN KEY (cuota_id) REFERENCES public.cuota(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 9MmMZHTI82twKUy7gpiJj8TLdrQ4C7cpF5nktIls8bZe6ckdkKgb880tNq3SJov

